### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by phid78** [marvinroger/hass-addon-tiko#1]
Bonjour et merci pour ton travail que j'ai testé hier.
Je suis sur l'integration de noiwid également.
Ma problematique est la suivante, j'ai un appartement transformé en 4 bureaux.
J'ai fait installé tiko via engie pour pouvoir gerer le termostast
J'ai besoin que chaque locataire puisse gerer son termostat (je le fait via une restriction kiosk pour qu'il n'ai acces qu'a leur bureau) en imposant des limites et je gere la programmation via schedulder.
J'aurai également besoin de couper un radiateur quand le local n'est pas loué (mais je crois que tilko ne l'autorise pas, donc actuellement j'ai programmé a 12°)
L'avantage de l'integration de noiwid c'est que j'ai pu imposer les limites  de chauffe max (22°, j'avoue que le mode boost a 25° de tiko me parait disproportionné surtout concernant les economies) mais aussi des modes pour facilité la programmation dans schedulder: 

```
tiko:
  climate:
    - 
      platform: generic_thermostat
      name: piece 1
      unique_id: climate_piece_1
      heater: switch.radiateurs_on
      target_sensor: sensor_piece_1_temperature
      min_temp: 7
      max_temp: 23
      away_temp: 17
      sleep_temp: 12
      home_temp : 20
      comfort_temp: 22
```
![image](https://github.com/marvinroger/hass-addon-tiko/assets/147193807/9c0b57d8-2bc1-4608-84c2-6a1db79050bd)

Un autre avantage est son historique de consommation et sa gestion global des modes (meme si je n'ai pas utilité dans mon cas)
L'avantage de la tienne est la consommation par radiateur et la gestion des modes par radiateurs (mais les modes prereglés par tiko ne me vont pas).
Aussi, noiwid ayant a priori peu de temps actuellement, penses tu pouvoir apporter cette amelioration : permettre des mini-maxi et des prereglage individuels ? si non permettre de recuperer que les mode et la consommation individuelle de chaque radiateur.
Les fetes approchants, et donc les vacances egalement, je vais devoir changer la programmation des radiateurs manuellement en fonction de l'absence des locataires (absence qu'ils n'ont aucune obligation de me communiquer, donc je risque de passer mes journée a jouer avec les radiateurs en fonction de leur presence)
