### ISSUE TITLE
Personnalisation des Presets

### ISSUE THREAD

**Issue by SylvainDx** [marvinroger/hass-addon-tiko#20]
Bonjour,

Serait-il possible de personnaliser les presets des entités climates ?

Dans l'idée, ajouter des icones de notre choix sur les différents modes existant, en ajouter certain avec des valeurs de température cible personnalisés ?

aujourd'hui j'ai un contournement avec le type de carte ci dessous mais cela permettrais d'utiliser les cartes climate standard plus facilement.

```entity: climate.salon_heating
type: custom:climate-mode-entity-row
name: "Modes :"
modes:
  - preset_mode: none
    icon: mdi:home-thermometer-outline
  - preset_mode: "off"
  - preset_mode: frostprotection
    icon: mdi:snowflake
  - preset_mode: away
    icon: mdi:exit-run
  - preset_mode: none
    temperature: 19
    icon: mdi:fire-circle
    color: "#FFC107"
  - preset_mode: boost
```

**Comment by marvinroger** [comment]
Bonjour,

Il n'est malheureusement pas possible de rajouter des icones personnalisées sur la carte de thermostat, les presets supportés étant codés en dur dans la carte.

Pour ce qui est des presets personnalisés, le but de cet add-on est de se rapprocher le plus possible de ce que propose l'API tiko, et l'API tiko ne permet pas de faire des presets custom. La personnalisation peut se faire avec les templates via de la config Home Assistant, mais c'est dans le périmètre fonctionnel de HASS, pas de cet add-on 😉

**Comment by SylvainDx** [comment]
Merci pour ta réponse!

**Comment by TheToto** [comment]
Petit workarround en utilisant card-mod pour les icones:

Ne fonctionne que pour un dashboard du coup, et non pour tout les autres vues.

```yaml
card_mod:
  style:
    hui-card-features$:
      hui-card-feature$:
        hui-climate-preset-modes-card-feature$:
          ha-control-select$: |
            #option-off { --card-mod-icon: mdi:power; }
            #option-none { --card-mod-icon: mdi:circle-outline; }
            #option-frostprotection { --card-mod-icon: mdi:snowflake; }
```

![Image](https://github.com/user-attachments/assets/8d64f506-00a5-48f3-9710-da2eda9c359c)
